backend:
  name: github
  repo: stechq/dist-plateau-mobile-android
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "docs/assets/images"
public_folder: "docs/assets/images"

collections:
  - name: "docs"
    label: "Dökümanlar"
    folder: "docs/_content/docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "İçerik", name: "body", widget: "markdown" }
      - { label: "Tarih", name: "date", widget: "datetime" }